name: test

on: [push, pull_request]

env:
  CONDA_CACHE_NUMBER: 0

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4
    - name: initialize conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: dropsonde_test
        auto-activate-base: false
        use-mamba: true
        miniforge-variant: Mambaforge
        miniforge-version: latest
    - name: install pip
      run: mamba install pip
    - name: install halodrops 
      run: python3 -m pip install git+https://github.com/Geet-George/halodrops.git 


           
     
